### ISSUE TITLE
Build problem on FreeBSD

### ISSUE THREAD

**Issue by cederom** [espressif/kconfig-frontends#4]
Hello world :-)

I have problems building this utility on FreeBSD:

```
% cmake CMakeLists.txt
-- The C compiler identification is Clang 11.0.1
-- The CXX compiler identification is Clang 11.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at cmake/FindGPERF.cmake:74 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  libs/parser/CMakeLists.txt:1 (find_package)


-- Found GPERF: /usr/local/bin/gperf (found version "3.1")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
-- Found BISON: /usr/local/bin/bison (found version "3.7.6")
-- Found Intl: /usr/local/lib/libintl.so (found version "0.21.0")
-- Found libregex: /usr/include
-- Found Curses: /usr/lib/libcurses.so
-- Configuring done
-- Generating done
-- Build files have been written to: /(...)/nuttx/dependencies/espressif-kconfig-frontends.git
0xCFMX4% make
[  6%] Building C object libs/expand_env/CMakeFiles/expand-env.dir/expand_env.c.o
[ 12%] Linking C static library libexpand-env.a
[ 12%] Built target expand-env
[ 18%] [GPERF][hconf] Building hash with gperf 3.1
[ 18%] Built target hconftarget
[ 25%] [FLEX][lconf] Building scanner with flex 2.6.4
[ 25%] Built target lconftarget
[ 31%] [BISON][yconf] Building parser with bison 3.7.6
/(...)/nuttx/dependencies/espressif-kconfig-frontends.git/libs/parser/yconf.y:34.1-7: warning: POSIX Yacc does not support %expect [%
```

Also it seems that `kconfig-frontends` is abandoned and unmaintained obsolete software. Why not use https://github.com/ulfalizer/Kconfiglib in IDF and NuttX?

**Comment by igrr** [comment]
Hi @cederom, in fact IDF does mainly rely on kconfiglib for Kconfig handling and `menuconfig`.

We use kconfig-frontends still in IDF only in one case: when IDF is installed on Windows in MSYS environment. This is because `menuconfig` from Kconfiglib doesn't work under MSYS.

Can you describe what led you to trying to compile this utility for freebsd?

**Comment by cederom** [comment]
Hello @igrr thank you for quick response! I am trying to build NuttX for ESP32-C3 on FreeBSD. Looks like this `kconfig-frontends` seems abandonware thanks for confirmation. I am also recommending NuttX to switch to https://github.com/ulfalizer/Kconfiglib :-)

**Comment by cederom** [comment]
Anyways, if they do not decide to switch to `kconfiglib` because of Python, your repository seems the only last one well maintained and updated, that may be the source origin for the FreeBSD's Port of `kconfig-frontends`.

I would like to first verify if that fork works correctly with current NuttX source tree. I have build problem, could you please hint me on the solution? :-)

**Comment by igrr** [comment]
Unfortunately I don't have a way to test this on FreeBSD, but I just built this project successfully on macOS and Linux.
Looking at your build log, seems to be something related to FreeBSD version of `bison`? I found this which looks related: https://github.com/paul-j-lucas/cdecl/issues/4.

**Comment by boris-kolpackov** [comment]
>your repository seems the only last one well maintained and updated, that may be the source origin for the FreeBSD's Port of kconfig-frontends.

FWIW, we maintain a "port" of upstream (i.e., linux) kconfig code with patches (some backported from this project) to make it work on a wide variety of platforms (including Windows):

https://github.com/build2-packaging/kconfig/tree/upstream-5.11-rc2

We also packaged the kconfig library (`liblkc`) and a number of configurators (`conf` and `qconf`) and they build fine on FreeBSD with `byacc`: https://queue.stage.build2.org/?builds=liblkc&cf=*freebsd*

**Comment by cederom** [comment]
Thank you guys! It seems this is the correct repository then to base port on. I am sure we will fix the build issue soon in FreeBSD :-) 

I would just like to make sure all functionalities of original `kconfig-frontends` preserved and we can use this repo as the "current" upstream? :-)

**Comment by cederom** [comment]
Hmm, I have fixed bison related problem by removing `bison -y` flag that turns on POSIX YACC emulation [1], but only `mconf-idf` binary is being built using CMake. Is it on purpose to only build this program without the others?

There is still old autoconf configuration in the repository. What is the purpose of keeping two build systems?

Is this package compatible with "original" `kconfig-frontends` and can be considered current upstream? Are you willing to maintain the project? Should I investigate further?

[1] https://github.com/cederom/kconfig-frontends/tree/cederom-freebsd-bison-fix

**Comment by cederom** [comment]
I have talked to Debian kconfig-frontends maintainer Philippe Thierry:

https://packages.debian.org/stable/kconfig-frontends

He confirmed that kconfig-frontends is abandoned. They use own git
repository with version 4.11.0.1 as current (seems more recent that this repository):

https://salsa.debian.org/philou/kconfig-frontends

Debian patches necessary to build are here (some additional patches
are necessary to GTK/GDK):

https://salsa.debian.org/philou/kconfig-frontends/-/tree/debian/master/debian/patches

**Comment by cederom** [comment]
I have sent email to Yann Morin the author of `kconfig-frontends` package asking if the project is really abandoned and if the maintenance can be passed to a new person / organization :-)

Current upstream seems down: https://ymorin.is-a-geek.org/projects/kconfig-frontends

**Comment by cederom** [comment]
I have created a FreeBSD port based on 4.11.0.1 release package: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259256

We may consider merging changes from both repos into one consistent project again when we figure out the upstream project status :-)

Thank you all for your time and support! :-)
